apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: dc-metro-map-lsmm
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dc-metro-map-lsmm
    app.kubernetes.io/part-of: dcmetromap
  name: dc-metro-map-lsmm
  namespace: shebert-tenant
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: dc-metro-map-lsmm
    weight: 100
status: {}
