apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/shebert-tenant/dcmetromap/dc-metro-map@sha256:6420e3edf6f1c86db82bc20294eb5e85612b5085f70b7dcaff72a763c4859a24
        name: my-nodejs
        resources: {}
status: {}
