apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map-lsmm
  namespace: shebert-tenant
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:cef8496e78c76cf87efaedbd687fa656e7dbc11f7b232e732eb1ed21e45af308
        name: container-image
        resources: {}
status: {}
