apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map-lsmm
  namespace: shebert-tenant
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:990cf29e73d5b1fb9485f14a896796ed6000f2985ee15fc13dd707b23884a69e
        name: container-image
        resources: {}
status: {}
