apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map-lsmm
  namespace: shebert-tenant
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:070b28bb406fe029cd50097547cc450db270e9133173306ffd37fb6d412e72c4
        name: container-image
        resources: {}
status: {}
