apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map-lsmm
  namespace: shebert-tenant
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:9afa060bf3faccf83e328fef42c6a30ca59786b4eaae3f7fd44b0f7145ddb6c0
        name: container-image
        resources: {}
status: {}
